"""Add profile_picture column

Revision ID: 58d171ef3d52
Revises: 3296e9d4b6e0
Create Date: 2025-01-22 02:57:35.993771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d171ef3d52'
down_revision = '3296e9d4b6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('execution_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('result', sa.JSON(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('request_log', schema=None) as batch_op:
        batch_op.drop_column('result')
        batch_op.drop_column('execution_time')
        batch_op.drop_column('test_type')

    # ### end Alembic commands ###
